// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJ6dPh8V7Mau-wvu5OouK4ZO0_lEUPPM',
    appId: '1:31015337595:web:be9e185b38cf0aa49eecde',
    messagingSenderId: '31015337595',
    projectId: 'green-day-2d59e',
    authDomain: 'green-day-2d59e.firebaseapp.com',
    storageBucket: 'green-day-2d59e.firebasestorage.app',
    measurementId: 'G-LPD65WZPPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjFqaPrwKtzw6ChlYNtZeQhapsBEQO4w',
    appId: '1:31015337595:android:cedd89018555fb579eecde',
    messagingSenderId: '31015337595',
    projectId: 'green-day-2d59e',
    storageBucket: 'green-day-2d59e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwbPjEuXPguZLyWePxo-YxnLh70kSXYsw',
    appId: '1:31015337595:ios:a56f0396c354a8909eecde',
    messagingSenderId: '31015337595',
    projectId: 'green-day-2d59e',
    storageBucket: 'green-day-2d59e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwbPjEuXPguZLyWePxo-YxnLh70kSXYsw',
    appId: '1:31015337595:ios:a56f0396c354a8909eecde',
    messagingSenderId: '31015337595',
    projectId: 'green-day-2d59e',
    storageBucket: 'green-day-2d59e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJ6dPh8V7Mau-wvu5OouK4ZO0_lEUPPM',
    appId: '1:31015337595:web:44cdb5a5e004d9ff9eecde',
    messagingSenderId: '31015337595',
    projectId: 'green-day-2d59e',
    authDomain: 'green-day-2d59e.firebaseapp.com',
    storageBucket: 'green-day-2d59e.firebasestorage.app',
    measurementId: 'G-MZPD7NMFK4',
  );
}
